MODEL:
  META_ARCHITECTURE: "RetinaNet"
  BACKBONE:
    NAME: "build_highroadside_fpn_backbone"
  FPN:
    IN_FEATURES: ["conv_stage1_out", "conv_stage2_out", "conv_stage3_out", "conv_stage4_out", "conv_stage5_out"]
    OUT_CHANNELS: 32
    FUSE_TYPE: "sum"
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: !!python/object/apply:eval ["[[x*2, x*2 * 2**(0.5), x*4 ] for x in [4, 8, 16, 32, 64]]"]
    ASPECT_RATIOS: [1, 2]
    ANGLES: [[0]]
    OFFSET: 0.5
  RETINANET:
    NUM_CLASSES: 6 #plate head tail car side_win win
    NUM_CONVS: 1
    IOU_THRESHOLDS: [0.4, 0.5]
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    SMOOTH_L1_LOSS_BETA: 2.75
    BBOX_REG_LOSS_TYPE: "smooth_l1"
    SCORE_THRESH_TEST: 0.5
    NMS_THRESH_TEST: 0.5
    TOPK_CANDIDATES_TEST: 1000
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
  PIXEL_MEAN: [0, 0, 0]
  PIXEL_STD: [0.00392156862745098, 0.00392156862745098, 0.00392156862745098]
  #WEIGHTS: "/detectron2/projects/HighRoadside/output/model_0034999.pth"
DATASETS:
  TRAIN: ("highroadside_dataset_train", "mix_dataset_train", )
  TEST: ("highroadside_dataset_val", "mix_dataset_val", )
DATALOADER:
  NUM_WORKERS: 1
  SAMPLER_TRAIN: "TrainingSampler"
  BLACK_MAGIC_CFG: "/detectron2/projects/HighRoadside/configs/H86_black.yaml"
  SAVE_BLACK_MAGIC_PATH: "" #"/detectron2/datasets/high_roadside/black_magic/"
SOLVER:
  IMS_PER_BATCH: 90
  BASE_LR: 0.1
  STEPS: (23000, 32000, 38000)
  MAX_ITER: 40000
  WEIGHT_DECAY: 0.0005
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
INPUT:
  FORMAT: "BGR"
TEST:
  DETECTIONS_PER_IMAGE: 450
VIS_PERIOD: 1000
VERSION: 2

